### ISSUE TITLE
will you opensource code 

### ISSUE THREAD

**Issue by wanghaisheng** [xellows1305/Document-Image-Dewarping#1]
i have tried your released exe and it is wonderful ,is there any plan to release code?

**Comment by taleslimaf** [comment]
Yeah. It ia really wonderfull. Could you release the code?

**Comment by Phreak87** [comment]
That would be great. Please provide the code

**Comment by Phreak87** [comment]
Maybe this is the binary from here:
http://ispl.snu.ac.kr/bskim/DocumentDewarping/

**Comment by haikuoyao** [comment]
yeah. Will you release your code?

**Comment by xxlxx1** [comment]
@wanghaisheng how to use the exe file?

**Comment by ZDDEAN** [comment]
+1

**Comment by zacharywhitley** [comment]
+1

**Comment by taeho-kil** [comment]
I don't have plans that release this source code, yet. Thanks.
