### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by mahmoudaljan** [xellows1305/Document-Image-Dewarping#14]
Hello,
Any plans on releasing a linux compatible executable ?

Thank you

**Comment by clarkk** [comment]
Yes, is it possible to get a linux compatible version?

Or could you release the source code? :)

**Comment by taeho-kil** [comment]
Thanks for your attention.
Unfortunately, there are no plans to release the source code at all. 
We developed this project with private company fundings, so can't release the source code without their consent.
I'm so sorry :)
